#!/bin/sh

# list files in long list (l), with human readable size units (h), omit backups (B)
# and sort version numbers naturally (v)
alias ls='ls -lhBv --group-directories-first --color=auto --time-style=+"%Y-%m-%d %H:%M"'
# list almost all but omit implied '.' and '..' (A)
alias la='ls -lhAv --group-directories-first --color=auto --time-style=+"%Y-%m-%d %H:%M"'

alias top='htop'
alias grep='grep --color=auto'
alias feh='feh --scale-down'

alias ping='ping -c 5'
alias fastping='ping -c 5 -s.2'

alias nowdate='date -I'
alias nowtime='date +"%T"'
alias nowdatetime='echo $(nowdate)_$(nowtime)'

alias df='df -HT --total'
alias du='du -hc'

alias emacs='emacs -nw'
alias vi='nvim'
alias vim='nvim'
alias e="$EDITOR"

alias unlock_pacman='rm /var/lib/pacman/db.lck'

alias notebook='jupyter notebook'

alias latexmk='latexmk -pvc -f -pdf -synctex=1 -interaction=batchmode'

# downloads a youtube video and extracts its audio stream.
# configure in ~/.config/youtube-dl.conf
alias yta='youtube-dl --extract-audio'

# alternative pass call with alternative password-store location
alias pass_ftb='PASSWORD_STORE_DIR=${PASSWORD_STORE_DIR}_ftb pass'
