#!/bin/sh

# exa as ls drop-in replacement
alias ls='exa -lh --group-directories-first --git --time-style=long-iso'
alias la='exa -lah --group-directories-first --git --time-style=long-iso'

alias top='htop'
alias grep='grep --color=auto'
alias feh='feh --scale-down'

alias ping='ping -c 5'
alias fastping='ping -c 5 -s.2'

alias nowdate='date -I'
alias nowtime='date +"%T"'
alias nowdatetime='echo $(nowdate)_$(nowtime)'

alias df='df -HT --total'
alias du='du -hc'
alias egrep='grep -E'

alias emacs='emacs -nw'
alias vi='nvim'
alias vim='nvim'
alias e='$EDITOR'

# lf-wrapper to change dir on exit
# (Taken from Luke Smith: https://github.com/LukeSmithxyz)
lfcd ()
{
    tmp="$(mktemp)"
    lfrun -last-dir-path="$tmp" "$@"
    if [ -f "$tmp" ]; then
        dir="$(cat "$tmp")"
        rm -f "$tmp"
        [ -d "$dir" ] && [ "$dir" != "$(pwd)" ] && cd "$dir"
    fi
}
alias lf='lfcd'


# fuzzy change directory
alias fcd='cd $(find . -type d | fzf)'

# things that don't play well with conda's virtual environment
alias yay='conda deactivate && \yay'

# organise configs in home git repo
alias home='/usr/bin/git --git-dir=$HOME/.local/repos/dot_configs --work-tree=$HOME'
alias homeui='gitui -d $HOME/.local/repos/dot_configs -w $HOME'
alias h='home'
alias hui='homeui'
alias he='GIT_DIR=$HOME/.local/repos/dot_configs GIT_WORK_TREE=$HOME e'
alias him='GIT_DIR=$HOME/.local/repos/dot_configs GIT_WORK_TREE=$HOME nvim'

# edit configs quickly
alias vimrc='cd ~/.config/nvim/ && he && cd -'
alias zshrc='he ~/.config/zsh/.zshrc'
alias aliasrc='he ~/.config/shell/aliasrc'
alias autostart='he ~/.config/x11/xprofile'


alias unlock_pacman='rm /var/lib/pacman/db.lck'

alias notebook='jupyter notebook'

alias latexmk='latexmk -pvc -f -pdf -synctex=1 -interaction=batchmode'

# create a directory and cd into it
md() {[ -n "$1" ] && mkdir -p $@ && cd $1}

lower_case ()
{
  find . -name '*.*' -exec sh -c '
  a=$(echo "$0" | sed -r "s/([^.]*)\$/\L\1/");
  [ "$a" != "$0" ] && mv "$0" "$a" ' {} \;
}
alias photo_rename='exiftool -ext jpg -ext jpeg -ext nef -d %Y-%m-%d_%H-%M-%S%%-c.%%e "-filename<CreateDate" "-filename<datetimeoriginal" * && lower_case'

# Use $XINITRC variable for startx
alias startx='startx $XINITRC'
