#!/bin/sh

# exa as ls drop-in replacement
alias ls='eza -lh --group-directories-first --git --time-style=long-iso --icons always'
alias la='eza -lah --group-directories-first --git --time-style=long-iso --icons always'
alias lg='eza -lahg --group-directories-first --git --time-style=long-iso --icons always'

alias top='btop'
alias grep='grep --color=auto'
alias feh='feh --scale-down'

alias pw='pwgen -y 16'

alias ping='ping -c 5'
alias fastping='ping -c 5 -s.2'

alias nowdate='date -I'
alias nowtime='date +"%T"'
alias nowdatetime='echo $(nowdate)_$(nowtime)'

alias df='df -HT --total'
alias du='du -hc'
alias egrep='grep -E'

alias emacs='emacs -nw'
alias vi='nvim'
alias vim='nvim'
alias e='$EDITOR'
alias t='tmux'
alias jqp='jqp --theme catppuccin-mocha'
alias activate='source .venv/bin/activate'

# lf-wrapper to change dir on exit
# (Taken from Luke Smith: https://github.com/LukeSmithxyz)
lf ()
{
    tmp="$(mktemp)"
    /usr/bin/lf -last-dir-path="$tmp" "$@"
    if [ -f "$tmp" ]; then
        dir="$(cat "$tmp")"
        rm -f "$tmp"
        [ -d "$dir" ] && [ "$dir" != "$(pwd)" ] && cd "$dir"
    fi
}

# yazi-wrapper to change dir on exit
y ()
{
	local tmp="$(mktemp -t "yazi-cwd.XXXXXX")"
	yazi "$@" --cwd-file="$tmp"
	if cwd="$(cat -- "$tmp")" && [ -n "$cwd" ] && [ "$cwd" != "$PWD" ]; then
		cd -- "$cwd"
	fi
	rm -f -- "$tmp"
}


# things that don't play well with conda's virtual environment
alias yay='conda deactivate ; \yay'

# organise configs in home git repo
alias home='/usr/bin/git --git-dir=$HOME/.local/repos/dot_configs --work-tree=$HOME'
alias homeui='gitui -d $HOME/.local/repos/dot_configs -w $HOME'
alias h='home'
alias hui='homeui'
alias he='GIT_DIR=$HOME/.local/repos/dot_configs GIT_WORK_TREE=$HOME e'
alias him='GIT_DIR=$HOME/.local/repos/dot_configs GIT_WORK_TREE=$HOME nvim'

# edit configs quickly
alias vimrc='cd ~/.config/nvim/ && he && cd -'
alias zshrc='cd ~/.config/zsh/ && he .zshrc && cd -'
alias aliasrc='cd ~/.config/shell/ && he aliasrc && cd -'
alias autostart='cd ~/.config/hypr/ && he autostart.conf && cd -'
alias keybinds='cd ~/.config/hypr/ && he keybinds.conf && cd -'

alias stocks='cd /data/Notes/Finance/Stocks/ && e && cd -'
alias notes='cd /data/Notes/ && e && cd -'

alias unlock_pacman='sudo rm /var/lib/pacman/db.lck'

alias notebook='jupyter notebook'

alias latexmk='latexmk -pvc -f -pdf -synctex=1 -interaction=batchmode'

# create a directory and cd into it
mcd() {[ -n "$1" ] && mkdir -p $@ && cd $1}

lower_case ()
{
    find . -name '*.*' -exec sh -c '
    a=$(echo "$0" | sed -r "s/([^.]*)\$/\L\1/");
    [ "$a" != "$0" ] && mv "$0" "$a" ' {} \;
}
alias photo_rename='exiftool -ext jpg -ext jpeg -ext nef -d %Y-%m-%d_%H-%M-%S%%-c.%%e "-filename<CreateDate" "-filename<datetimeoriginal" * && lower_case'

# Use $XINITRC variable for startx
alias startx='startx $XINITRC'
