#!/bin/sh

# Adds all paths in `~/.local/bin` to $PATH, except for X and wayland specific folders
# those will be added in their respective init scripts
export PATH="$PATH:$(du "$HOME/.local/bin" | cut -f2 | grep -Ev "(x11)|(wayland)" | paste -sd ':' -)"


export TERMINAL="alacritty"
export EDITOR="nvim"
export BROWSER="brave"
# lfrun: lf-wrapper script to enable preview of images and pdfs
export FILE="lfrun"
# open a new terminal and run lf in it
export FILE_CMD="$TERMINAL -e $FILE"

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export XINITRC="${XDG_CONFIG_HOME}/x11/xinitrc"
export XPROFILE="${XDG_CONFIG_HOME}/x11/xprofile"
export XRESOURCES="${XDG_CONFIG_HOME}/x11/xresources"
export XDG_DATA_DIRS=/usr/share:${XDG_DATA_HOME}
export WALLPAPER=${XDG_DATA_HOME}/wallpaper

export GTK2_RC_FILES="${XDG_CONFIG_HOME}/gtk-2.0/gtkrc-2.0"
export ZDOTDIR="${XDG_CONFIG_HOME}/zsh"
export ZHISTDIR="${XDG_CACHE_HOME}/zsh"
export GNUPGHOME="${XDG_DATA_HOME}/gnupg"
export PASSWORD_STORE_DIR=${XDG_DATA_HOME}/password-store


# Use bat (https://github.com/sharkdp/bat) as viewer for manpages
export MANPAGER="sh -c 'col -bx | bat -l man -p'"


export PYTHONIOENCODING=UTF-8
export HISTCONTROL=ignoredups

# local folder to look up latex packages
export TEXMFHOME=${XDG_DATA_HOME}/texfm/

# This is the list for lf icons:
# taken from the lf wiki and modified by myself
LF_ICONS=$(sed ~/.local/share/file_icons -e '/^[ \t]*#/d' -e '/^[ \t]*$/d' -e 's/[ \t]\+/=/g' | tr '\n' ':')
export LF_ICONS
