#!/bin/sh

# add scripts for controlling the display in an X session
PATH=$PATH:$HOME/.local/bin/x11

# if external monitor is connected, set as main and switch off internal one

# switch off screen blanking
xset dpms 0 0 0
xset s off
xset s noblank

# load resources like colour schemes
[ -f ${XRESOURCES} ] && xrdb -merge ${XRESOURCES}

# autostarting user applications happens here
[ -f ${XPROFILE} ] && . ${XPROFILE}


session=${1:-dwm}

case $session in
    i3|i3wm           ) ssh-agent i3 ;;
    dwm               ) ssh-agent dwm ;;
    # No known session, try to run it as command
    *                 ) exec $1;;
esac
