#!/bin/sh

# the notification daemon.
dunst &
# Enable compositing.
picom --vsync -b

# UDisks front-end for automounting removable media.
udiskie -ans &
# music player daemon
mpd

# unclutter hides the mouse curser after timeout
unclutter --timeout 7 --ignore-scrolling -b

{
    sleep 1
    # Launch web browser
    ${BROWSER} &

    # Launch music player
    cantata &
} &

# polybar
# needs a second to be ready and read the window title correctly
{
    sleep 1
    polybar_start &
} &

# NetworkManager Tray Icon
{
    sleep 2
    nm-applet &
} &

# Launch telegram
# needs a second to show systray icon
{
    sleep 2
    telegram-desktop &
} &

# KDE Connect
{
    sleep 2
    /usr/lib/kdeconnectd &
    kdeconnect-indicator &
    sleep 10
    kdeconnect-cli --refresh
    kdeconnect-cli -l
} &

# start background slideshow
{
    while true;
    do
        setbg
        sleep 600
    done
} &

loop_bg &
