#!/bin/sh

# the notification daemon.
dunst &
# Enable compositing.
picom --vsync -b

# UDisks front-end for automounting removable media.
udiskie -ans &

# music player daemon
mpd
cantata &

# unclutter hides the mouse curser after timeout
unclutter --timeout 7 --ignore-scrolling -b

# web browser
{
    sleep 1
    ${BROWSER} &
} &

# polybar
# needs a second to be ready and read the window title correctly
{
    sleep 1
    polybar_start &
} &

# NetworkManager Tray Icon
{
    sleep 2
    nm-applet &
} &

# Launch telegram
# needs a second to show systray icon
{
    sleep 2
    telegram-desktop &
} &

# KDE Connect
{
    sleep 2
    kdeconnect-startup &
} &

# start background slideshow
{
    while true;
    do
        setbg
        sleep 600
    done
} &

loop_bg &
