add_newline = false

palette = "catppuccin_mocha"
format = """$directory$character"""
right_format = """$git_branch$git_commit $git_status $git_metrics $git_state$python$conda $time"""

[directory]
truncation_length = 8
truncation_symbol = '…/'


[time]
disabled = false
format = '[$time]($style)'
time_format = '%T'

[git_branch]
disabled = false
symbol = ''
format = '[$symbol$branch(:$remote_branch)]($style)'
ignore_branches = ['master', 'main']

[git_commit]
disabled = false
only_detached = true
format = '[\($hash$tag\)]($style)'

[git_metrics]
disabled = false
format = '([+$added]($added_style))([-$deleted]($deleted_style))'

[git_state]
disabled = false

[git_status]
disabled = false
format = '([\[$all_status$ahead_behind\]]($style))'

[python]
disabled = false
symbol = '🐍'
format = '[${symbol} ${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[conda]
disabled = false
format = '[$environment]($style)'


[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
