#!/bin/sh

# to run on external GPU
xrandr --setprovideroutputsource modesetting NVIDIA-0
xrandr --auto
xrandr --dpi 96

# add scripts for controlling the display in an X session
PATH=$PATH:/home/ichanmich/.local/bin/x11

# switch off screen blanking
{
    sleep 1
    xset dpms 0 0 0
} &

# load resources like colour schemes
[ -f ${XRESOURCES} ] && xrdb -merge ${XRESOURCES}

# autostarting user applications happens here
[ -f ${XPROFILE} ] && . ${XPROFILE}


session=${1:-dwm}

case $session in
    i3|i3wm           ) ssh-agent i3 ;;
    dwm               ) ssh-agent dwm ;;
    # No known session, try to run it as command
    *                 ) exec $1;;
esac
