#!/bin/sh

# the notification daemon.
dunst &
# Enable compositing.
picom -b

# UDisks front-end for automounting removable media.
udiskie -ans &
# music player daemon
# (seems to get started by something else already)
# mpd &

# NetworkManager Tray Icon
nm-applet &
# KDE Connect
kdeconnect-indicator &

# polybar
polybar bottom_dwm &
polybar top_bar &
# Launch web browser
brave &
# Launch editor
code &
# Launch music player
cantata &
# Launch telegram
telegram-desktop &

# start background slideshow
{
    while true;
    do
        setbg
        sleep 600
    done
} &
