#!/bin/sh

# the notification daemon.
dunst &
# Enable compositing.
picom -b

# UDisks front-end for automounting removable media.
udiskie -ans &
# music player daemon
mpd

# unclutter hides the mouse curser after timeout
unclutter --timeout 7 --ignore-scrolling -b

# Launch web browser
${BROWSER} &

# Launch music player
cantata &

# NetworkManager Tray Icon
nm-applet &

# polybar
# needs a second to be ready and read the window title correctly
{
    sleep 1
    polybar bottom_dwm &
    polybar top_bar &
} &

# Launch telegram
# needs a second to show systray icon
{
    sleep 3
    telegram-desktop &
} &

# KDE Connect
/usr/lib/kdeconnectd &
kdeconnect-indicator &
{
    sleep 5
    # still doesn't reliably recognise phone sometimes
    kdeconnect-cli --refresh
    kdeconnect-cli -l
} &

# start background slideshow
{
    while true;
    do
        setbg
        sleep 600
    done
} &
